post https://band-setlist.herokuapp.com/api/bands
Content-Type: application/json
Accept: application/json

{
    "username": "Beatles",
    "name": "Beatles",
    "password": "m3rseyBeat4",
    "securityQuestion": "F famous club in Liverpool",
    "securityAnswer": "Cavern"
}

