post http://localhost:3003/api/blogs
Content-Type: application/json
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpa3VzYXJsaW4iLCJpZCI6IjVmNDU0ZmRmYTQ4YWRmNDY1NDNlZTNmNCIsImlhdCI6MTU5ODM3ODM0MH0.Jzl3gIUD5w4HvazJiQLjiPMBFonDteqrdUIx5byqne0

{
    "title":"Micro frontends",
    "author":"Cam Jackson",
    "url":"https://martinfowler.com/articles/micro-frontends.html",
    "likes":"10"
}


