post http://localhost:3003/api/pieces
Content-Type: application/json
Accept: application/json
Authorization: bearer xxx

{
    "title":"Simpler Man v2",
    "artist":"Lynyrd Skynyrd",
    "delay": 25,
    "duration":270,
    "pages":[
        {
            "pageNumber":1,
            "rows":[
                {
                    "rowNumber": 1,
                    "rowType": "Chords",
                    "contents": "       C            G            Am"
                }
            ]
        }
    ],
    "notes":[
        {
            "instrument":"Guitar",
            "rows":[
                {
                    "rowNumber": 1,
                    "contents": "Finger picking"
                }
            ]
        }
    ]
}


