post http://localhost:3003/api/setlist
Content-Type: application/json
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlbGEiLCJpYXQiOjE2NTc0NTIwODV9.3ivby4xtHgIq15GPVhLnja0Y4Li3n9MMoI2VnmLHWkY

{
    "name":"IT Christmas party 2021-11-26"
}


