delete http://localhost:3003/api/pieces/621a7bf138c72f4bece7eac3
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpa3UiLCJpZCI6IjYyMWE1MjE4NDk5ZDhmNDcyZDU4MGUwYiIsImlhdCI6MTY0NTg5ODIzNX0.8opHC6XlbvksaKQ1LrjPEifKiEGzRy2L_uizanpcWP4
