put http://localhost:3003/api/setlist/f8337048-acbb-443a-a154-e4c037bc3d54/bae103d8-afb5-4eb5-a3d1-71012b72be5a/down
Content-Type: application/json
Accept: application/json
Authorization: bearer xxx



