put http://localhost:3003/api/blogs/5dfcded7c311a752b5429d89
Content-Type: application/json
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVsc2Euc2FybGluIiwiaWQiOiI1ZGZjZDVjNzdmZjE1ZjRjNjRhNTU5ZmYiLCJpYXQiOjE1Nzg5Mzg2MTJ9.b4CvIfknUd6ZEvzs_ovjsDs6mamAHVF6DHI8PAlMVIg

{
    "title":"Kela, Jumalasta seuraava",
    "author":"Riku Sarlin",
    "url":"https://sinetti.kela.fi/blogs/Kela_jumalasta_seuraava",
    "likes":"34"
}


